{
    "checksum": "d163189f641a17740960884005625427adae0a3ca21077f59a28881b826bf906",
    "file": "exceptions.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 5,
    "package": "python-muranoclient",
    "path": "python-muranoclient/2.3.0-2/muranoclient/common/exceptions.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-muranoclient/2.3.0-2/",
        "metric": {
            "size": 1324
        },
        "pts_link": "https://tracker.debian.org/pkg/python-muranoclient",
        "sloc": [
            [
                "python",
                10822
            ],
            [
                "sh",
                232
            ],
            [
                "makefile",
                27
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/clients/python-muranoclient",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-muranoclient/2.3.0-2/muranoclient/common/exceptions.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 4982,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "2.3.0-2"
}