{
    "checksum": "7a3c0b9686b6259885db00db6a623e0b0eacd773a0bb9e0def5385e7163abef3",
    "file": "persist-error-message-cda8dfe485fe92ba.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 4,
    "package": "python-troveclient",
    "path": "python-troveclient/1:7.1.1-2/releasenotes/notes/persist-error-message-cda8dfe485fe92ba.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-troveclient/1:7.1.1-2/",
        "metric": {
            "size": 1820
        },
        "pts_link": "https://tracker.debian.org/pkg/python-troveclient",
        "sloc": [
            [
                "python",
                17185
            ],
            [
                "sh",
                75
            ],
            [
                "makefile",
                15
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/clients/python-troveclient",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-troveclient/1%3A7.1.1-2/releasenotes/notes/persist-error-message-cda8dfe485fe92ba.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 92,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1:7.1.1-2"
}