{
    "checksum": "4b4f643264325fd230a2926cb8e5c5075a0391de41e08a05dd41c363e5489373",
    "file": "exceptions.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 5,
    "package": "qgis",
    "path": "qgis/3.16.15+dfsg-1/python/plugins/processing/modeler/exceptions.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/qgis/3.16.15+dfsg-1/",
        "metric": {
            "size": 814172
        },
        "pts_link": "https://tracker.debian.org/pkg/qgis",
        "sloc": [
            [
                "cpp",
                1144458
            ],
            [
                "python",
                173601
            ],
            [
                "xml",
                13652
            ],
            [
                "perl",
                3382
            ],
            [
                "sh",
                3088
            ],
            [
                "sql",
                2446
            ],
            [
                "ansic",
                2199
            ],
            [
                "yacc",
                1021
            ],
            [
                "lex",
                570
            ],
            [
                "javascript",
                505
            ],
            [
                "lisp",
                411
            ],
            [
                "makefile",
                233
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/debian-gis-team/qgis",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/q/qgis/3.16.15%2Bdfsg-1/python/plugins/processing/modeler/exceptions.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 956,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "3.16.15+dfsg-1"
}