{
    "checksum": "c19043964d51ea4f760a9df605f8cb374fca4be2bf592001e973e957bbc5736c",
    "file": "test_failure.py",
    "mime": {
        "encoding": "utf-8",
        "type": "text/x-python"
    },
    "number_of_duplicates": 3,
    "package": "python-taskflow",
    "path": "python-taskflow/4.6.2-2/taskflow/tests/unit/test_failure.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-taskflow/4.6.2-2/",
        "metric": {
            "size": 3428
        },
        "pts_link": "https://tracker.debian.org/pkg/python-taskflow",
        "sloc": [
            [
                "python",
                27271
            ],
            [
                "sh",
                237
            ],
            [
                "makefile",
                23
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/libs/python-taskflow",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-taskflow/4.6.2-2/taskflow/tests/unit/test_failure.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 18465,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "4.6.2-2"
}