{
    "checksum": "f00ea600617c66932d1ed933281d5bdc3f69655e901eb0df3f53e0147fc79625",
    "file": "pyverbs_error.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 2,
    "package": "rdma-core",
    "path": "rdma-core/36.0-1/pyverbs/pyverbs_error.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/rdma-core/36.0-1/",
        "metric": {
            "size": 11068
        },
        "pts_link": "https://tracker.debian.org/pkg/rdma-core",
        "sloc": [
            [
                "ansic",
                152058
            ],
            [
                "python",
                7556
            ],
            [
                "sh",
                2761
            ],
            [
                "perl",
                1465
            ],
            [
                "makefile",
                73
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://github.com/linux-rdma/rdma-core",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/r/rdma-core/36.0-1/pyverbs/pyverbs_error.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 1503,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "36.0-1"
}