{
    "checksum": "cfede2e0c741639c21d2de62c6b84f195de145f687a69ce092494b48e4aa7f72",
    "file": "InvalidDNSnameConstraintsTest31EE.p12",
    "mime": {
        "encoding": "binary",
        "type": "application/octet-stream"
    },
    "number_of_duplicates": 6,
    "package": "python-cryptography-vectors",
    "path": "python-cryptography-vectors/3.4.8-1/cryptography_vectors/x509/PKITS_data/pkcs12/InvalidDNSnameConstraintsTest31EE.p12",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-cryptography-vectors/3.4.8-1/",
        "metric": {
            "size": 78852
        },
        "pts_link": "https://tracker.debian.org/pkg/python-cryptography-vectors",
        "sloc": [
            [
                "python",
                61
            ],
            [
                "sh",
                49
            ],
            [
                "makefile",
                3
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/python-cryptography-vectors",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-cryptography-vectors/3.4.8-1/cryptography_vectors/x509/PKITS_data/pkcs12/InvalidDNSnameConstraintsTest31EE.p12",
    "stat": {
        "perms": "rw-r--r--",
        "size": 2769,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": false,
    "type": "file",
    "version": "3.4.8-1"
}