{
    "checksum": "b2a8099d6ef46adcc2d43d506e497d8bc330e7edb38fbbf0e35f1477fe361f18",
    "file": "exceptions.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 2,
    "package": "django-websocket-redis",
    "path": "django-websocket-redis/0.4.7-2/ws4redis/exceptions.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/django-websocket-redis/0.4.7-2/",
        "metric": {
            "size": 204
        },
        "pts_link": "https://tracker.debian.org/pkg/django-websocket-redis",
        "sloc": [
            [
                "python",
                885
            ],
            [
                "makefile",
                3
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/modules/django-websocket-redis",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/d/django-websocket-redis/0.4.7-2/ws4redis/exceptions.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 540,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.4.7-2"
}