{
    "checksum": "b9afb136a05865af2255586af63b22c74615fe95deed64d19f1a94de22518f79",
    "file": "exceptions.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 2,
    "package": "python-miio",
    "path": "python-miio/0.5.0.1-2/miio/exceptions.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-miio/0.5.0.1-2/",
        "metric": {
            "size": 1288
        },
        "pts_link": "https://tracker.debian.org/pkg/python-miio",
        "sloc": [
            [
                "python",
                14798
            ],
            [
                "makefile",
                20
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/miio",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-miio/0.5.0.1-2/miio/exceptions.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 478,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.5.0.1-2"
}